// <auto-generated />
using Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(ReceptkonyvContext))]
    partial class ReceptkonyvContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Kategorium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("nev");

                    b.HasKey("Id")
                        .HasName("PK__kategori__3213E83FDF7D555F");

                    b.ToTable("kategoria", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Recept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KatId")
                        .HasColumnType("int")
                        .HasColumnName("kat_id");

                    b.Property<string>("KepEleresiUt")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("kep_eleresi_ut");

                    b.Property<string>("Leiras")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("leiras");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nev");

                    b.HasKey("Id")
                        .HasName("PK__recept__3213E83F8E7CE522");

                    b.HasIndex("KatId");

                    b.ToTable("recept", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Recept", b =>
                {
                    b.HasOne("Backend.Models.Kategorium", "Kat")
                        .WithMany("Recepts")
                        .HasForeignKey("KatId")
                        .IsRequired()
                        .HasConstraintName("FK__recept__kat_id__267ABA7A");

                    b.Navigation("Kat");
                });

            modelBuilder.Entity("Backend.Models.Kategorium", b =>
                {
                    b.Navigation("Recepts");
                });
#pragma warning restore 612, 618
        }
    }
}
